name: test

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  pull_request_target:
    types: [labeled]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "GitHub event: ${{ toJson(github) }}"
        echo ${{ github.event_name }}=="workflow_dispatch"
